export const STORE_GENERAL_DATA = 'STORE_GENERAL_DATA';
export const STORE_FIRST_DATA = 'STORE_FIRST_DATA';
export const STORE_SECOND_DATA = 'STORE_SECOND_DATA';
export const CHANGE_SECTION = 'CHANGE_SECTION';